!     -*- f90 -*-
!     This file is autogenerated with f2py (version:1.26.4)
!     It contains Fortran 90 wrappers to fortran functions.

      subroutine f2pywrap_bspline_FindSpan (FindSpanf2pywrap, n, p, uu, &
     &U)
      use bspline, only : FindSpan
      integer(kind=4) n
      integer(kind=4) p
      real(kind=8) uu
      real(kind=8) U(2 + n + p)
      integer(kind=4) FindSpanf2pywrap
      FindSpanf2pywrap = FindSpan(n, p, uu, U)
      end subroutine f2pywrap_bspline_FindSpan
      subroutine f2pywrap_bspline_FindMult (FindMultf2pywrap, i, uu, p, &
     &U)
      use bspline, only : FindMult
      integer(kind=4) i
      real(kind=8) uu
      integer(kind=4) p
      real(kind=8) U(2 + i + p)
      integer(kind=4) FindMultf2pywrap
      FindMultf2pywrap = FindMult(i, uu, p, U)
      end subroutine f2pywrap_bspline_FindMult
      
      subroutine f2pyinitbspline(f2pysetupfunc)
      use bspline, only : FindSpanMult
      use bspline, only : BasisFuns
      use bspline, only : DersBasisFuns
      use bspline, only : CurvePoint
      use bspline, only : SurfacePoint
      use bspline, only : CurvePntByCornerCut
      use bspline, only : InsertKnot
      use bspline, only : RemoveKnot
      use bspline, only : ClampKnot
      use bspline, only : UnclampKnot
      use bspline, only : RefineKnotVector
      use bspline, only : DegreeElevate
      interface 
      subroutine f2pywrap_bspline_FindSpan (FindSpanf2pywrap, n, p, uu, &
     &U)
      integer(kind=4) n
      integer(kind=4) p
      real(kind=8) uu
      real(kind=8) U(2 + n + p)
      integer(kind=4) FindSpanf2pywrap
      end subroutine f2pywrap_bspline_FindSpan 
      subroutine f2pywrap_bspline_FindMult (FindMultf2pywrap, i, uu, p, &
     &U)
      integer(kind=4) i
      real(kind=8) uu
      integer(kind=4) p
      real(kind=8) U(2 + i + p)
      integer(kind=4) FindMultf2pywrap
      end subroutine f2pywrap_bspline_FindMult
      end interface
      external f2pysetupfunc
      call f2pysetupfunc(f2pywrap_bspline_FindSpan,f2pywrap_bspline_Find&
     &Mult,FindSpanMult,BasisFuns,DersBasisFuns,CurvePoint,SurfacePoint,&
     &CurvePntByCornerCut,InsertKnot,RemoveKnot,ClampKnot,UnclampKnot,Re&
     &fineKnotVector,DegreeElevate)
      end subroutine f2pyinitbspline

      subroutine f2pywrap_bspeval_Determinant (Determinantf2pywrap, dim,&
     & A)
      use bspeval, only : Determinant
      integer(kind=4) dim
      real(kind=8) A(dim,dim)
      real(kind=8) Determinantf2pywrap
      Determinantf2pywrap = Determinant(dim, A)
      end subroutine f2pywrap_bspeval_Determinant
      subroutine f2pywrap_bspeval_Inverse (Inversef2pywrap, dim, A)
      use bspeval, only : Inverse
      integer(kind=4) dim
      real(kind=8) A(dim,dim)
      real(kind=8) Inversef2pywrap(dim,dim)
      Inversef2pywrap = Inverse(dim, A)
      end subroutine f2pywrap_bspeval_Inverse
      
      subroutine f2pyinitbspeval(f2pysetupfunc)
      use bspeval, only : TensorProd1
      use bspeval, only : TensorProd2
      use bspeval, only : TensorProd3
      use bspeval, only : Rationalize
      use bspeval, only : GeometryMap
      use bspeval, only : Interpolate
      interface 
      subroutine f2pywrap_bspeval_Determinant (Determinantf2pywrap, dim,&
     & A)
      integer(kind=4) dim
      real(kind=8) A(dim,dim)
      real(kind=8) Determinantf2pywrap
      end subroutine f2pywrap_bspeval_Determinant 
      subroutine f2pywrap_bspeval_Inverse (Inversef2pywrap, dim, A)
      integer(kind=4) dim
      real(kind=8) A(dim,dim)
      real(kind=8) Inversef2pywrap(dim,dim)
      end subroutine f2pywrap_bspeval_Inverse
      end interface
      external f2pysetupfunc
      call f2pysetupfunc(TensorProd1,TensorProd2,TensorProd3,Rationalize&
     &,GeometryMap,Interpolate,f2pywrap_bspeval_Determinant,f2pywrap_bsp&
     &eval_Inverse)
      end subroutine f2pyinitbspeval

      
      subroutine f2pyinitBSp(f2pysetupfunc)
      use BSp, only : FindSpan
      use BSp, only : FindMult
      use BSp, only : FindSpanMult
      use BSp, only : EvalBasisFuns
      use BSp, only : EvalBasisFunsDers
      use BSp, only : SpanIndex
      use BSp, only : Greville
      use BSp, only : InsertKnot
      use BSp, only : RemoveKnot
      use BSp, only : Clamp
      use BSp, only : Unclamp
      use BSp, only : RefineKnotVector
      use BSp, only : DegreeElevate
      use BSp, only : Extract
      use BSp, only : Evaluate0
      use BSp, only : Evaluate1
      use BSp, only : Evaluate2
      use BSp, only : Evaluate3
      use BSp, only : Gradient1
      use BSp, only : Gradient2
      use BSp, only : Gradient3
      use BSp, only : Hessian1
      use BSp, only : Hessian2
      use BSp, only : Hessian3
      use BSp, only : ThirdDer1
      use BSp, only : ThirdDer2
      use BSp, only : ThirdDer3
      use BSp, only : FourthDer1
      use BSp, only : FourthDer2
      use BSp, only : FourthDer3
      external f2pysetupfunc
      call f2pysetupfunc(FindSpan,FindMult,FindSpanMult,EvalBasisFuns,Ev&
     &alBasisFunsDers,SpanIndex,Greville,InsertKnot,RemoveKnot,Clamp,Unc&
     &lamp,RefineKnotVector,DegreeElevate,Extract,Evaluate0,Evaluate1,Ev&
     &aluate2,Evaluate3,Gradient1,Gradient2,Gradient3,Hessian1,Hessian2,&
     &Hessian3,ThirdDer1,ThirdDer2,ThirdDer3,FourthDer1,FourthDer2,Fourt&
     &hDer3)
      end subroutine f2pyinitBSp

      
      subroutine f2pyinitIGA(f2pysetupfunc)
      use IGA, only : KnotVector
      use IGA, only : GaussLegendreRule
      use IGA, only : GaussLobattoRule
      use IGA, only : BasisData
      use IGA, only : Greville
      use IGA, only : BasisDataCol
      external f2pysetupfunc
      call f2pysetupfunc(KnotVector,GaussLegendreRule,GaussLobattoRule,B&
     &asisData,Greville,BasisDataCol)
      end subroutine f2pyinitIGA


